server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: game-engine-route
            uri: lb://game-engine-service-app
            predicates:
              - Path=/api/games/**

          - id: game-session-route
            uri: lb://game-session-service-app
            predicates:
              - Path=/api/sessions/**

          - id: ui-route
            uri: lb://ui-service-app
            predicates:
              - Path=/**
