server:
  port: 8082

spring:
  application:
    name: game-session-service-app
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
