server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamesessiondb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
